### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTUwNzIyM2UxYmZiZjE3OWE3MDhlNzAiLCJpYXQiOjE2NDMyNjIwMDIsImV4cCI6MTY0MzYyMjAwMn0.cx--0JCI0dsyiTjI3wFs7lhQv8LVbDtc040vx5wpRP0
@login = { "email": "hello@email.com", "password": "password" }

### Get authenticated user given the token
GET  http://localhost:5000/api/auth
x-auth-token: {{token}}

### Login user and get token
POST  http://localhost:5000/api/auth
content-type: application/json

{{login}}